### PR TITLE
Fixed routes for precompiled assets in 3.1

### PR DESCRIPTION
**Pull request by georgedrummond**
Fixed image helper to the sprite file to work on 3.1 using scss instead of css.erb

### CODE REVIEW

**Comment by stefanoverna** [comment]
+1 fixes the problem. @thetron, could you please merge this?

**Comment by thetron** [comment]
Thanks for this fix and testing guys. Much appreciated.

**Comment by stefanoverna** [comment]
Cool, when it will be released as a gem update?

**Comment by thetron** [comment]
Soon, I hope! I want to try and sort through the remaining issues & pull requests before I push out the next release. I also want to try adding a couple of other tests, but I'm super keen to get this release wrapped up ASAP.

**Pull request merged**
