### PR TITLE
rails3.1+ asset pipeline support

### PR DESCRIPTION
**Pull request by florianguenther**
finally I made my version backward compatible so now it's ready to merge!

### CODE REVIEW

**Comment by thetron** [comment]
Thanks again florian - I'll merge it in when I get a chance to sit down proper and take a look. :)

**Comment by azolotov** [comment]
+1

**Comment by torzech** [comment]
What about that 3.1? :)

**Comment by thetron** [comment]
I have been terrible at staying on top of this - my _real_ job has been craaaaazy, but I am officially (finally) merging this in now. Doing some tests to make sure everything came across cleanly, but hoping to have 1.0.0 out very soon.

**Comment by thetron** [comment]
This has all been merged in, but git seems to have squashed some of the commits, but thanks @florianguenther !! Really, really appreciate your work here.

**Pull request closed without merging**
